language: java
dist: xenial
jdk:
- openjdk11
addons:
  sonarcloud:
    organization: sumned
    token:
      secure: "u8JYww5j/YqpK40n8BB3RzmyOmDzzLki7LjvxmLqg4QlFvpqDxiaRpnO8CJPKrfc/5QjHQaazXO+diVJgKHBZbBmvEyK7i0qP/oyAwNpgABZbvU2g1AHMgqPe/HdRSAwPs1yy2eq0lYZueDAQYWRFPu0GFyFkaed5
              6IR3Vkv3NXWJ5YdSCQcvDmkQixumU+TQuYbw7V0Q62J3UsjeKYAJGJg5S8pVsc7fQv0rgg0yAnLH3DdhYxfo7Ubn9vy/HGnsFdhvAC1TTd4iNKOk431+EkfH+uULF0juKoQfisMQAW8k2Zako0afE4l97NpiDjG5IexGDhhC11/Z
              y23w0G8rXmN1KzHdV8K233sLbbbSBjM7TH1e81rB28DNezCmzTv26fajrgpxfXEqSKst0ayuDLAj/GL5KyIpTIWN0ojQYDtx6IT0MRy17wDBCqWl5BdQ5BL8+sOFC79eKno+UDRbifHetozB2LwWZoLpGRQVAQ7wtkOSs/33uqX4
              /kPsAN5oT5r87/FENQi+5wI00C/OUYjUYfQl2wP3hSVrXUhv5Vb7rvPmtLflsb7H69qIuuNRYHnIZX3C+PEs6IljVyIz2GbMke7f2rjE0+/uYNus6MvbSULzPMT6m/R5Lj4luwa8dFIlPuvtoIWqe4Mc+xowD5ZmgMkiyWdr5hW/
              s4jVN0="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Sumned_jv_hibernate_cinema
cache:
  directories:
  - "$HOME/.m2"
