language: java
dist: xenial
jdk:
- openjdk11
addons:
  sonarcloud:
    organization: sumned
    token:
      secure: SA6txUuq6l5g0E+01nHvPxQccvLCgwpz5klbQVeTiQccidLlYTisMGpLuQmJGE1mpzpmmqHaijGwmSNbOtiYku3gVP6rZU0/fhnNhfz+OXm5JgIrkCd+mp2Cf9icUGjvP/dGx8pE74BZFk6+4+byoKM/fzBUQk0LOJxNTesCIX4j11Sqo/s4EwlUO1912RVSTmL7LG9b4zRZ+r3fcZeMT1w1YzYC1dL0NBUzGuRClYNglDQ51nfWQp/MrdU+44F4ElizNG/8M+LU7VHDgjetwnYp2yFOySwFbzZzu2MReMEHdTngchJS+ja9pT2O/rsksk5o5F3qTXvh1w+34a75s+GC5J+lNEKC55PZV5qA7Ykt7tmM98aAfmyx6KBOWHFaSnwVf0uU8i0s5l+WMQBGcP+VE+QfC0PgjJKbFB5JQveqa/DCEWIjyF6hnRpxsk8uRU3pd/v1qMCNy0NmYHnWuzKptluxCZK2x6qtyq+gRcznCkOU5EpkduB81wn4y/KErwdQs7cQutJfxz4MpN4Jq3obTF0k7Drp4qUCCn8D9lev1RlfGHc7rLcdV3F2aqbrYwQIff90xFbGsAx8WTQLOjiMXBB8MB4JOkSaLVVdkyzzJqee3KB350w3EKdI2I5CEfBAsQ9woWBKjDDiNL6zNWNXP4KQwDFBpUi4H8lEwO4=
script:
- mvn clean install
- sonar-scanner
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: v68rA0PVfdPSFkublNk8KHb0LkA04Ub0o0vHUAP6FwdSv2F/qHO7CscgaNuuZTUNAWUww53aq1Dfn4VEsDU87KjK42rsDSNiGNatDnk/Sde0AKmYAx5c6Wk4xir/fDZ5N/atf0yT9QeJBhQuwyzXRzaIMt5KFhp0rZxq8WqRY3ijTRSnCj6BbBnEY1lXetDQAlR3/Hn+eHx49YIWAVLKOgPdhxPaYFTXzghYJLVTaET/QbZ4CkTzs8JaeAJi1tcW0Qqo65u6KetBRyP3v2cziUXVLKX5zkKvGKtVe4PpzNZhWNMfNH39UiGPh1lKf02jK7vL0/emYZihJdP7yGCMX3CrV1h3+iRmaIbzs+FUjR7P+JzSYAP4Tj3uvbBbCCIx5BAM70IAkvQpRMELkF4QiFsRO3zogZO7xH6HF5FeLHXaUaveXxBllHAqsUqWqAgxV9jZ6qETFuolxj8ABDsmwGaJVi6ygcATE6m6fC2Oxd7pBrqN9aQe72h9Tt4efpwp9zaDptBaDoIMzz8nQXIjIPDUIieptk8rBU86c1vaASFnm83sdrC7E4p5i5n1AdhC7jYv9VR6Hn6eEjWTpX8vjPYRLqIEDsG6seQsgwh8g4cmy831s4l27DqZOKVVLwcA9QkkXhlNVTS9xe1kF4l6CGbZjDix8LJijuY0OmB3XNw=
  - secure: SA6txUuq6l5g0E+01nHvPxQccvLCgwpz5klbQVeTiQccidLlYTisMGpLuQmJGE1mpzpmmqHaijGwmSNbOtiYku3gVP6rZU0/fhnNhfz+OXm5JgIrkCd+mp2Cf9icUGjvP/dGx8pE74BZFk6+4+byoKM/fzBUQk0LOJxNTesCIX4j11Sqo/s4EwlUO1912RVSTmL7LG9b4zRZ+r3fcZeMT1w1YzYC1dL0NBUzGuRClYNglDQ51nfWQp/MrdU+44F4ElizNG/8M+LU7VHDgjetwnYp2yFOySwFbzZzu2MReMEHdTngchJS+ja9pT2O/rsksk5o5F3qTXvh1w+34a75s+GC5J+lNEKC55PZV5qA7Ykt7tmM98aAfmyx6KBOWHFaSnwVf0uU8i0s5l+WMQBGcP+VE+QfC0PgjJKbFB5JQveqa/DCEWIjyF6hnRpxsk8uRU3pd/v1qMCNy0NmYHnWuzKptluxCZK2x6qtyq+gRcznCkOU5EpkduB81wn4y/KErwdQs7cQutJfxz4MpN4Jq3obTF0k7Drp4qUCCn8D9lev1RlfGHc7rLcdV3F2aqbrYwQIff90xFbGsAx8WTQLOjiMXBB8MB4JOkSaLVVdkyzzJqee3KB350w3EKdI2I5CEfBAsQ9woWBKjDDiNL6zNWNXP4KQwDFBpUi4H8lEwO4=
